name: Upload Python File to GitHub

on:
  workflow_dispatch: # Memungkinkan Anda untuk menjalankan workflow secara manual

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload .py file to GitHub
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.PYTOEXETOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"message": "Upload .py file", "content": "$CONTENT"}' \
          https://api.github.com/repos/eroge69/PyToExe/contents/uploads/$FILE_NAME
        env:
          CONTENT: ${{ github.event.inputs.content }}
          FILE_NAME: ${{ github.event.inputs.fileName }}
