name: Build Python to EXE

on:
  push:
    branches:
      - main  # Jalankan pada push ke cabang main
  pull_request:
    branches:
      - main  # Jalankan pada pull request ke cabang main
  workflow_dispatch:  # Memungkinkan manual trigger dari GitHub UI

jobs:
  build:
    runs-on: windows-latest  # Gunakan runner Windows terbaru

    steps:
    # Langkah 1: Checkout kode sumber dari repositori
    - name: Checkout code
      uses: actions/checkout@v3

    # Langkah 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Tentukan versi Python yang diinginkan

    # Langkah 3: Cache pip dependencies (menghindari instalasi ulang)
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip  # Lokasi cache pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}  # Gunakan hash dari requirements.txt sebagai key cache
        restore-keys: |
          ${{ runner.os }}-python-

    # Langkah 4: Install dependensi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Install PyInstaller jika belum ada di cache

    # Langkah 5: Temukan file .py yang terakhir di-upload
    - name: Find the latest Python script
      id: find_latest
      run: |
        # Temukan file Python (.py) terbaru di repositori
        latest_file=$(find . -type f -name "*.py" -print0 | xargs -0 ls -t | head -n 1)
        echo "Latest Python script: $latest_file"
        echo "::set-output name=script::$latest_file"

    # Langkah 6: Build file EXE dengan PyInstaller
    - name: Build EXE
      run: |
        # Gunakan file Python yang ditemukan dari langkah sebelumnya
        pyinstaller --onefile --distpath dist --workpath build --specpath spec ${{ steps.find_latest.outputs.script }}

    # Langkah 7: Upload file .exe sebagai artifact
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/*.exe  # Ganti dengan nama file EXE yang sesuai
