name: Py to Exe Conversion

on:
  issues:
    types: [opened]

jobs:
  convert-py-to-exe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create EXE from Python script
        run: |
          echo "Downloading .py file from Issue Body..."
          echo "Simulated process of fetching the uploaded file."
          echo "Use the file directly if it is attached in the issue."

          # Simulate file creation for this example
          echo "print('Hello, World!')" > script.py

          # Convert script to EXE
          pyinstaller --onefile script.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-to-exe
          path: dist/script.exe

      - name: Create GitHub Issue without token
        run: |
          response=$(curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -d '{"title": "Convert file to EXE", "body": "Conversion of uploaded Python file to EXE."}' \
          https://api.github.com/repos/eroge69/PyToExe/issues)

          echo "Response: $response"

          # Optionally, check if response contains any error
          if echo "$response" | grep -q "error"; then
            echo "Error occurred: $response"
            exit 1
          fi
