name: Build Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branchRef:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Langkah 1: Checkout kode
    - name: Checkout code
      uses: actions/checkout@v4

    # Langkah 2: Create requirements.txt first
    - name: Create requirements.txt
      run: |
        echo "pyinstaller" > requirements.txt
      shell: powershell

    # Langkah 3: Setup Python - explicitly specify 3.10.x
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Langkah 4: Verify Python version
    - name: Verify Python version
      run: |
        python --version
        pip --version
      shell: powershell

    # Langkah 5: Cache pip packages
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Langkah 6: Install dependencies directly (no venv)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: powershell

    # Langkah 7: Cache PyInstaller build files
    - name: Cache PyInstaller build files
      uses: actions/cache@v3
      with:
        path: |
          build
          spec
        key: ${{ runner.os }}-pyinstaller-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-pyinstaller-

    # Langkah 8: Temukan file Python terbaru menggunakan PowerShell
    - name: Find the latest Python script
      id: find_latest
      run: |
        $latest_file = Get-ChildItem -Recurse -Filter "*.py" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        echo "Latest Python script: $($latest_file.FullName)"
        echo "script=$($latest_file.FullName)" >> $env:GITHUB_OUTPUT
      shell: powershell

    # Langkah 9: Build EXE dengan PyInstaller
    - name: Build EXE
      run: |
        $script_path="${{ steps.find_latest.outputs.script }}"
        $output_dir=(Split-Path -Path $script_path)
        pyinstaller --onefile --distpath $output_dir --workpath build --specpath spec $script_path
      shell: powershell

    # Langkah 10: Upload EXE as artifact
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: exe-file
        path: |
          **/*.exe

    # Langkah 11: Post message with download link
    - name: Post download link
      run: |
        echo "Your file has been uploaded as an artifact."
        echo "You can download it from: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

