name: Build Python to EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Memungkinkan trigger manual dari GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout kode sumber dari repositori
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Tentukan versi Python yang diinginkan

    # Install dependensi
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    # Build file EXE dengan PyInstaller
    - name: Build EXE
      run: |
        pyinstaller --onefile --distpath dist --workpath build --specpath spec my_script.py

    # Upload file .exe sebagai artifact
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/my_script.exe
