name: Convert Python to EXE

on:
  repository_dispatch:
    types: [convert_to_exe]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Convert Python to EXE
        run: |
          python -m PyInstaller --onefile ${{ github.event.client_payload.file }}
      
      - name: Upload EXE file
        uses: actions/upload-artifact@v2
        with:
          name: python-exe
          path: dist/*.exe
